#!/bin/bash

echo 'Cleaning node_modules...'
npm prune

echo 'Updating node_modules...'
npm install

echo 'Cleaning bower_components...'
node_modules/.bin/bower prune --allow-root

echo 'Updating bower_components...'
node_modules/.bin/bower install --allow-root

echo 'Building server assets...'
node_modules/.bin/cogs -c cogs-server.json

echo 'Building client assets...'
node_modules/.bin/cogs -c cogs-client.json
