postgres:
  image: postgres:9.4
  volumes:
    - var/postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - '5432'

nginx:
  image: nginx:1.7.9
  ports:
    - '80:80'
  volumes:
    - etc/nginx.conf:/etc/nginx/nginx.conf
    - public:/usr/share/nginx/html
  links:
    - app

cogsclient:
  image: node:0.12.0-slim
  volumes:
    - .:/src
  working_dir: /src
  command: node_modules/.bin/cogs -c cogs-client.js -pw src

cogsserver:
  image: node:0.12.0-slim
  volumes:
    - .:/src
  working_dir: /src
  command: node_modules/.bin/cogs -c cogs-server.js -pw src

app:
  image: node:0.12.0-slim
  volumes:
    - .:/src
  working_dir: /src
  links:
    - postgres
  ports:
    - '3000'
  environment:
    POSTGRES_URL: postgres://postgres:postgres@postgres/postgres
  command: node_modules/.bin/watchy -pw build -- node build/node_modules
