version: '3'

volumes:
  pg-data:

services:
  postgres:
    image: postgres:9.6.2
    volumes:
      - pg-data:/var/lib/postgresql/data

  client: &client
    # image: coderiety/bruteball:master
    image: 081168c4c5db
    depends_on:
      - signal
    environment:
      WATCH: 1
    ports:
      - 80:80
    volumes:
      - ./.eslintrc:/code/.eslintrc
      - ./.stylelintrc:/code/.stylelintrc
      - ./bin:/code/bin
      - ./etc:/code/etc
      - ./package.json:/code/package.json
      - ./src:/code/src

  signal:
    <<: *client
    environment:
      COMMAND: signal
      WATCH: 1
    depends_on:
      - postgres
    ports:
      - 8080:80
