postgres:
  image: postgres:9.4
  volumes:
    - var/postgres:/var/lib/postgresql/data
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
  ports:
    - '5432'

cogsclient:
  image: node:0.12.1
  volumes:
    - .:/code
  working_dir: /code
  command: node_modules/.bin/cogs -c cogs-client.js -pw src

cogsserver:
  image: node:0.12.1
  volumes:
    - .:/code
  working_dir: /code
  command: node_modules/.bin/cogs -c cogs-server.js -pw src

app:
  image: node:0.12.1
  volumes:
    - .:/code
  working_dir: /code
  links:
    - postgres
  ports:
    - '80:80'
  environment:
    AWS_ACCESS_KEY_ID:
    AWS_SECRET_ACCESS_KEY:
    POSTGRES_URL: postgres://postgres:postgres@postgres/postgres
    PORT: '80'
  command: node_modules/.bin/watchy -pw build -- make start
